server:
  shutdown: graceful

#spring:
#  lifecycle:
#    timeout-per-shutdown-phase: 30s

management:
  endpoints:
    web:
      #      base-path: "/"
      exposure:
        include: "*"
  endpoint:
    shutdown:
      enabled: true
    health:
      show-details: always